# ------------------------------------------------------------------------------ 
#  Copyright (c) Microsoft Corporation.  All Rights Reserved.  
#  Licensed under the MIT License.  See License in the project root for license information. 
# ------------------------------------------------------------------------------ 
function Enable-EntraAzureADAliases {
   Set-Alias -Name Get-AzureADMSRoleDefinition -Value Get-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSRoleAssignment -Value Remove-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedResource -Value Get-EntraBetaPrivilegedResource -Scope Global -Force
   Set-Alias -Name New-AzureADMSRoleDefinition -Value New-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraBetaPrivilegedRoleAssignmentRequest -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSRoleDefinition -Value Remove-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedRoleSetting -Value Get-EntraBetaPrivilegedRoleSetting -Scope Global -Force
   Set-Alias -Name Get-AzureADMSRoleAssignment -Value Get-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADPrivilegedRole -Value Get-EntraBetaPrivilegedRole -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedRoleDefinition -Value Get-EntraBetaPrivilegedRoleDefinition -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPrivilegedRoleSetting -Value Set-EntraBetaPrivilegedRoleSetting -Scope Global -Force
   Set-Alias -Name Set-AzureADMSRoleDefinition -Value Set-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPrivilegedRoleAssignmentRequest -Value Set-EntraBetaPrivilegedRoleAssignmentRequest -Scope Global -Force
   Set-Alias -Name New-AzureADMSRoleAssignment -Value New-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name New-AzureADPrivilegedRoleAssignment -Value New-EntraBetaPrivilegedRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-CrossCloudVerificationCode -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationPasswordCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExtensionProperty -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationServiceEndpoint -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Restore-AzureADMSDeletedDirectoryObject -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADPrivilegedRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorMemberOf -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Close-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceConfiguration -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationSingleSignOn -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Open-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationCustomDomainCertificate -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Add-AzureADMSPrivilegedResource -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroupMembers -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADCurrentSessionInfo -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADContactManager -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADContactThumbnailPhoto -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaRoleAssignment -Value Remove-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleAssignment -Value Get-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name New-EntraBetaRoleAssignment -Value New-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Set-EntraBetaRoleDefinition -Value Set-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleDefinition -Value Get-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaRoleDefinition -Value Remove-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name New-EntraBetaRoleDefinition -Value New-EntraBetaDirectoryRoleDefinition -Scope Global -Force

}
