# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
  - task: UseDotNet@2
    displayName: "Use .NET 2" # needed for ESRP signing
    inputs:
      version: 2.x

  - task: UseDotNet@2
    displayName: Use .NET SDK
    inputs:
      debugMode: false
      version: 7.x

  - task: NuGetToolInstaller@1
    displayName: Install Nuget

  - task: NuGetAuthenticate@1

  - task: PowerShell@2
    displayName: Version Check
    inputs:
      targetType: inline
      pwsh: true
      script: |
        Write-Output $PSVersionTable

