# ------------------------------------------------------------------------------ 
#  Copyright (c) Microsoft Corporation.  All Rights Reserved.  
#  Licensed under the MIT License.  See License in the project root for license information. 
# ------------------------------------------------------------------------------ 
function Enable-EntraAzureADAliases {
   Set-Alias -Name Set-AzureADMSCustomSecurityAttributeDefinition -Value Set-EntraBetaCustomSecurityAttributeDefinition -Scope Global -Force
   Set-Alias -Name Remove-AzureADAdministrativeUnit -Value Remove-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name Get-AzureADMSRoleDefinition -Value Get-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Add-AzureADDeviceRegisteredUser -Value Add-EntraBetaDeviceRegisteredUser -Scope Global -Force
   Set-Alias -Name Get-AzureADContactDirectReport -Value Get-EntraBetaContactDirectReport -Scope Global -Force
   Set-Alias -Name Set-AzureADMSCustomSecurityAttributeDefinitionAllowedValue -Value Set-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name Get-AzureADAdministrativeUnitMember -Value Get-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Get-AzureADContract -Value Get-EntraBetaContract -Scope Global -Force
   Set-Alias -Name Get-AzureADContact -Value Get-EntraBetaContact -Scope Global -Force
   Set-Alias -Name Get-AzureADContactManager -Value Get-EntraBetaContactManager -Scope Global -Force
   Set-Alias -Name Add-AzureADAdministrativeUnitMember -Value Add-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Set-AzureADMSAdministrativeUnit -Value Set-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name New-AzureADDevice -Value New-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name Get-AzureADDevice -Value Get-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name Get-AzureADMSAttributeSet -Value Get-EntraBetaAttributeSet -Scope Global -Force
   Set-Alias -Name Get-AzureADDomainVerificationDnsRecord -Value Get-EntraBetaDomainVerificationDnsRecord -Scope Global -Force
   Set-Alias -Name Get-AzureADMSCustomSecurityAttributeDefinition -Value Get-EntraBetaCustomSecurityAttributeDefinition -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceRegisteredUser -Value Get-EntraBetaDeviceRegisteredUser -Scope Global -Force
   Set-Alias -Name Get-AzureADScopedRoleMembership -Value Get-EntraBetaScopedRoleMembership -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectorySetting -Value Get-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues -Value Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name Remove-AzureADDirectorySetting -Value Remove-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Set-AzureADMSAttributeSet -Value Set-EntraBetaAttributeSet -Scope Global -Force
   Set-Alias -Name New-AzureADMSAdministrativeUnitMember -Value New-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Remove-AzureADContact -Value Remove-EntraBetaContact -Scope Global -Force
   Set-Alias -Name Set-AzureADDomain -Value Set-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Add-AzureADScopedRoleMembership -Value Add-EntraBetaScopedRoleMembership -Scope Global -Force
   Set-Alias -Name New-AzureADMSAttributeSet -Value New-EntraBetaAttributeSet -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectorySettingTemplate -Value Get-EntraBetaDirectorySettingTemplate -Scope Global -Force
   Set-Alias -Name Get-AzureADTenantDetail -Value Get-EntraBetaTenantDetail -Scope Global -Force
   Set-Alias -Name Set-AzureADTenantDetail -Value Set-EntraBetaTenantDetail -Scope Global -Force
   Set-Alias -Name Get-AzureADMSRoleAssignment -Value Get-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name New-AzureADMSCustomSecurityAttributeDefinition -Value New-EntraBetaCustomSecurityAttributeDefinition -Scope Global -Force
   Set-Alias -Name Remove-AzureADDomain -Value Remove-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Confirm-AzureADDomain -Value Confirm-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name New-AzureADMSAdministrativeUnit -Value New-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name Remove-AzureADScopedRoleMembership -Value Remove-EntraBetaScopedRoleMembership -Scope Global -Force
   Set-Alias -Name Add-AzureADDeviceRegisteredOwner -Value Add-EntraBetaDeviceRegisteredOwner -Scope Global -Force
   Set-Alias -Name Remove-AzureADAdministrativeUnitMember -Value Remove-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Get-AzureADSubscribedSku -Value Get-EntraBetaSubscribedSku -Scope Global -Force
   Set-Alias -Name Set-AzureADDirectorySetting -Value Set-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Remove-AzureADDevice -Value Remove-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name Get-AzureADDomainNameReference -Value Get-EntraBetaDomainNameReference -Scope Global -Force
   Set-Alias -Name New-AzureADDomain -Value New-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectoryRoleTemplate -Value Get-EntraBetaDirectoryRoleTemplate -Scope Global -Force
   Set-Alias -Name Get-AzureADDomain -Value Get-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Get-AzureADMSCustomSecurityAttributeDefinitionAllowedValue -Value Get-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name Remove-AzureADDeviceRegisteredOwner -Value Remove-EntraBetaDeviceRegisteredOwner -Scope Global -Force
   Set-Alias -Name Add-AzureADDirectoryRoleMember -Value Add-EntraBetaDirectoryRoleMember -Scope Global -Force
   Set-Alias -Name New-AzureADDirectorySetting -Value New-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceRegisteredOwner -Value Get-EntraBetaDeviceRegisteredOwner -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectoryRoleMember -Value Get-EntraBetaDirectoryRoleMember -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectoryRole -Value Get-EntraBetaDirectoryRole -Scope Global -Force
   Set-Alias -Name Enable-AzureADDirectoryRole -Value Enable-EntraBetaDirectoryRole -Scope Global -Force
   Set-Alias -Name Get-AzureADContactMembership -Value Get-EntraBetaContactMembership -Scope Global -Force
   Set-Alias -Name Remove-AzureADDeviceRegisteredUser -Value Remove-EntraBetaDeviceRegisteredUser -Scope Global -Force
   Set-Alias -Name Get-AzureADDomainServiceConfigurationRecord -Value Get-EntraBetaDomainServiceConfigurationRecord -Scope Global -Force
   Set-Alias -Name Set-AzureADDevice -Value Set-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name Get-AzureADMSDeletedDirectoryObject -Value Get-EntraBetaDeletedDirectoryObject -Scope Global -Force
   Set-Alias -Name Remove-AzureADDirectoryRoleMember -Value Remove-EntraBetaDirectoryRoleMember -Scope Global -Force
   Set-Alias -Name Get-AzureADAdministrativeUnit -Value Get-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name Get-CrossCloudVerificationCode -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationPasswordCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExtensionProperty -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationServiceEndpoint -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Restore-AzureADMSDeletedDirectoryObject -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADPrivilegedRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorMemberOf -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Close-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceConfiguration -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationSingleSignOn -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Open-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationCustomDomainCertificate -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Add-AzureADMSPrivilegedResource -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroupMembers -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADCurrentSessionInfo -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADContactManager -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADContactThumbnailPhoto -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleAssignment -Value Get-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleDefinition -Value Get-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValues -Value Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force

}
