# ------------------------------------------------------------------------------ 
#  Copyright (c) Microsoft Corporation.  All Rights Reserved.  
#  Licensed under the MIT License.  See License in the project root for license information. 
# ------------------------------------------------------------------------------ 
function Enable-EntraAzureADAlias {
   Set-Alias -Name Get-AzureADMSRoleAssignment -Value Get-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Add-AzureADMSFeatureRolloutPolicyDirectoryObject -Value Add-EntraBetaFeatureRolloutPolicyDirectoryObject -Scope Global -Force
   Set-Alias -Name Get-AzureADUserThumbnailPhoto -Value Get-EntraBetaUserThumbnailPhoto -Scope Global -Force
   Set-Alias -Name Set-AzureADTenantDetail -Value Set-EntraBetaTenantDetail -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSIdentityProvider -Value Remove-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPermissionGrantPolicy -Value Set-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationSignInDetailedSummary -Value Get-EntraBetaApplicationSignInDetailedSummary -Scope Global -Force
   Set-Alias -Name Set-AzureADDirectorySetting -Value Set-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Remove-AzureADUserAppRoleAssignment -Value Remove-EntraBetaUserAppRoleAssignment -Scope Global -Force
   Set-Alias -Name New-AzureADMSCustomSecurityAttributeDefinition -Value New-EntraBetaCustomSecurityAttributeDefinition -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSApplicationKey -Value Remove-EntraBetaApplicationKey -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplication -Value Remove-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationOwner -Value Remove-EntraBetaApplicationOwner -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationKeyCredential -Value New-EntraBetaApplicationKeyCredential -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSServicePrincipalDelegatedPermissionClassification -Value Remove-EntraBetaServicePrincipalDelegatedPermissionClassification -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectoryRole -Value Get-EntraBetaDirectoryRole -Scope Global -Force
   Set-Alias -Name Enable-AzureADDirectoryRole -Value Enable-EntraBetaDirectoryRole -Scope Global -Force
   Set-Alias -Name New-AzureADGroupAppRoleAssignment -Value New-EntraBetaGroupAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalOwner -Value Get-EntraBetaServicePrincipalOwner -Scope Global -Force
   Set-Alias -Name New-AzureADMSGroup -Value New-EntraBetaGroup -Scope Global -Force
   Set-Alias -Name Reset-AzureADMSLifeCycleGroup -Value Reset-EntraBetaLifeCycleGroup -Scope Global -Force
   Set-Alias -Name Get-AzureADAuditSignInLogs -Value Get-EntraBetaAuditSignInLog -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationLogo -Value Set-EntraBetaApplicationLogo -Scope Global -Force
   Set-Alias -Name Set-AzureADMSNamedLocationPolicy -Value Set-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectoryRoleTemplate -Value Get-EntraBetaDirectoryRoleTemplate -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSFeatureRolloutPolicy -Value Remove-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADDirectorySetting -Value New-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Set-AzureADServicePrincipal -Value Set-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name New-AzureADMSTrustFrameworkPolicy -Value New-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name Select-AzureADGroupIdsUserIsMemberOf -Value Select-EntraBetaGroupIdsUserIsMemberOf -Scope Global -Force
   Set-Alias -Name Remove-AzureADDeletedApplication -Value Remove-EntraBetaDeletedApplication -Scope Global -Force
   Set-Alias -Name New-AzureADMSPermissionGrantConditionSet -Value New-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name Set-AzureADDomain -Value Set-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Get-AzureADUserRegisteredDevice -Value Get-EntraBetaUserRegisteredDevice -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationPasswordCredential -Value New-EntraBetaApplicationPasswordCredential -Scope Global -Force
   Set-Alias -Name Set-AzureADMSAuthorizationPolicy -Value Set-EntraBetaAuthorizationPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationKeyCredential -Value Remove-EntraBetaApplicationKeyCredential -Scope Global -Force
   Set-Alias -Name Confirm-AzureADDomain -Value Confirm-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalPasswordCredential -Value Remove-EntraBetaServicePrincipalPasswordCredential -Scope Global -Force
   Set-Alias -Name Add-AzureADApplicationPolicy -Value Add-EntraBetaApplicationPolicy -Scope Global -Force
   Set-Alias -Name Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues -Value Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name Select-AzureADGroupIdsGroupIsMemberOf -Value Select-EntraBetaGroupIdsGroupIsMemberOf -Scope Global -Force
   Set-Alias -Name Remove-AzureADUserExtension -Value Remove-EntraBetaUserExtension -Scope Global -Force
   Set-Alias -Name Get-AzureADDomainVerificationDnsRecord -Value Get-EntraBetaDomainVerificationDnsRecord -Scope Global -Force
   Set-Alias -Name Get-AzureADMSApplicationTemplate -Value Get-EntraBetaApplicationTemplate -Scope Global -Force
   Set-Alias -Name Get-AzureADDomain -Value Get-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalPolicy -Value Remove-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalPolicy -Value Get-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSPasswordSingleSignOnCredential -Value New-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedRoleSetting -Value Get-EntraBetaPrivilegedRoleSetting -Scope Global -Force
   Set-Alias -Name Get-AzureADObjectSetting -Value Get-EntraBetaObjectSetting -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplicationPassword -Value New-EntraBetaApplicationPassword -Scope Global -Force
   Set-Alias -Name Get-AzureADUserCreatedObject -Value Get-EntraBetaUserCreatedObject -Scope Global -Force
   Set-Alias -Name Get-AzureADMSDeletedDirectoryObject -Value Get-EntraBetaDeletedDirectoryObject -Scope Global -Force
   Set-Alias -Name Get-AzureADMSAttributeSet -Value Get-EntraBetaAttributeSet -Scope Global -Force
   Set-Alias -Name New-AzureADMSAdministrativeUnit -Value New-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name Remove-AzureADScopedRoleMembership -Value Remove-EntraBetaScopedRoleMembership -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipal -Value New-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name Remove-AzureADServiceAppRoleAssignment -Value Remove-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyApplication -Value Get-EntraBetaApplicationProxyApplication -Scope Global -Force
   Set-Alias -Name Select-AzureADGroupIdsContactIsMemberOf -Value Select-EntraBetaGroupIdsContactIsMemberOf -Scope Global -Force
   Set-Alias -Name Remove-AzureADGroup -Value Remove-EntraBetaGroup -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPasswordSingleSignOnCredential -Value Get-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectoryRoleMember -Value Get-EntraBetaDirectoryRoleMember -Scope Global -Force
   Set-Alias -Name Set-AzureADMSApplication -Value Set-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name Get-AzureADMSLifecyclePolicyGroup -Value Get-EntraBetaLifecyclePolicyGroup -Scope Global -Force
   Set-Alias -Name Remove-AzureADTrustedCertificateAuthority -Value Remove-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraBetaPrivilegedRoleAssignmentRequest -Scope Global -Force
   Set-Alias -Name Get-AzureADAdministrativeUnitMember -Value Get-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedRoleDefinition -Value Get-EntraBetaPrivilegedRoleDefinition -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSNamedLocationPolicy -Value Remove-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADDomainNameReference -Value Get-EntraBetaDomainNameReference -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipal -Value Get-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name New-AzureADMSAdministrativeUnitMember -Value New-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Get-AzureADUser -Value Get-EntraBetaUser -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSRoleAssignment -Value Remove-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalCreatedObject -Value Get-EntraBetaServicePrincipalCreatedObject -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplicationFromApplicationTemplate -Value New-EntraBetaApplicationFromApplicationTemplate -Scope Global -Force
   Set-Alias -Name Get-AzureADServiceAppRoleAssignment -Value Get-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Revoke-AzureADUserAllRefreshToken -Value Revoke-EntraBetaUserAllRefreshToken -Scope Global -Force
   Set-Alias -Name Get-AzureADMSAuthorizationPolicy -Value Get-EntraBetaAuthorizationPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSApplicationPassword -Value Remove-EntraBetaApplicationPassword -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSApplicationVerifiedPublisher -Value Remove-EntraBetaApplicationVerifiedPublisher -Scope Global -Force
   Set-Alias -Name Get-AzureADUserOwnedObject -Value Get-EntraBetaUserOwnedObject -Scope Global -Force
   Set-Alias -Name Get-AzureADUserLicenseDetail -Value Get-EntraBetaUserLicenseDetail -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalPasswordCredential -Value Get-EntraBetaServicePrincipalPasswordCredential -Scope Global -Force
   Set-Alias -Name Revoke-AzureADSignedInUserAllRefreshToken -Value Revoke-EntraBetaSignedInUserAllRefreshToken -Scope Global -Force
   Set-Alias -Name Get-AzureADUserMembership -Value Get-EntraBetaUserMembership -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalOAuth2PermissionGrant -Value Get-EntraBetaServicePrincipalOAuth2PermissionGrant -Scope Global -Force
   Set-Alias -Name Set-AzureADMSIdentityProvider -Value Set-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSGroupLifecyclePolicy -Value Remove-EntraBetaGroupLifecyclePolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSCustomSecurityAttributeDefinitionAllowedValue -Value Get-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name Set-AzureADUserExtension -Value Set-EntraBetaUserExtension -Scope Global -Force
   Set-Alias -Name Set-AzureADMSGroup -Value Set-EntraBetaGroup -Scope Global -Force
   Set-Alias -Name Set-AzureADObjectSetting -Value Set-EntraBetaObjectSetting -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSPermissionGrantPolicy -Value Remove-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSGroupLifecyclePolicy -Value Set-EntraBetaGroupLifecyclePolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSAttributeSet -Value New-EntraBetaAttributeSet -Scope Global -Force
   Set-Alias -Name Get-AzureADGroupOwner -Value Get-EntraBetaGroupOwner -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationOwner -Value Get-EntraBetaApplicationOwner -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationSignInSummary -Value Get-EntraBetaApplicationSignInSummary -Scope Global -Force
   Set-Alias -Name Add-AzureADGroupMember -Value Add-EntraBetaGroupMember -Scope Global -Force
   Set-Alias -Name Get-AzureADUserManager -Value Get-EntraBetaUserManager -Scope Global -Force
   Set-Alias -Name Get-AzureADSubscribedSku -Value Get-EntraBetaSubscribedSku -Scope Global -Force
   Set-Alias -Name Get-AzureADMSRoleDefinition -Value Get-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Add-AzureADDeviceRegisteredUser -Value Add-EntraBetaDeviceRegisteredUser -Scope Global -Force
   Set-Alias -Name Get-AzureADGroupMember -Value Get-EntraBetaGroupMember -Scope Global -Force
   Set-Alias -Name Set-AzureADUserManager -Value Set-EntraBetaUserManager -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationExtensionProperty -Value New-EntraBetaApplicationExtensionProperty -Scope Global -Force
   Set-Alias -Name New-AzureADMSGroupLifecyclePolicy -Value New-EntraBetaGroupLifecyclePolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSRoleDefinition -Value Set-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Set-AzureADMSApplicationVerifiedPublisher -Value Set-EntraBetaApplicationVerifiedPublisher -Scope Global -Force
   Set-Alias -Name Get-AzureADGroupAppRoleAssignment -Value Get-EntraBetaGroupAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSPermissionGrantConditionSet -Value Remove-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name Get-AzureADContactManager -Value Get-EntraBetaContactManager -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalOwner -Value Remove-EntraBetaServicePrincipalOwner -Scope Global -Force
   Set-Alias -Name New-AzureADMSFeatureRolloutPolicy -Value New-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADPolicy -Value Set-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSRoleDefinition -Value Remove-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Add-AzureADDirectoryRoleMember -Value Add-EntraBetaDirectoryRoleMember -Scope Global -Force
   Set-Alias -Name Add-AzureADDeviceRegisteredOwner -Value Add-EntraBetaDeviceRegisteredOwner -Scope Global -Force
   Set-Alias -Name Get-AzureADObjectByObjectId -Value Get-EntraBetaObjectByObjectId -Scope Global -Force
   Set-Alias -Name Get-AzureADTrustedCertificateAuthority -Value Get-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name New-AzureADUserAppRoleAssignment -Value New-EntraBetaUserAppRoleAssignment -Scope Global -Force
   Set-Alias -Name New-AzureADMSPermissionGrantPolicy -Value New-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplication -Value New-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name Get-AzureADTenantDetail -Value Get-EntraBetaTenantDetail -Scope Global -Force
   Set-Alias -Name Set-AzureADUserPassword -Value Set-EntraBetaUserPassword -Scope Global -Force
   Set-Alias -Name Get-AzureADPolicyAppliedObject -Value Get-EntraBetaPolicyAppliedObject -Scope Global -Force
   Set-Alias -Name Get-AzureADServiceAppRoleAssignedTo -Value Get-EntraBetaServicePrincipalAppRoleAssignedTo -Scope Global -Force
   Set-Alias -Name Get-AzureADMSGroupLifecyclePolicy -Value Get-EntraBetaGroupLifecyclePolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSGroupPermissionGrant -Value Get-EntraBetaGroupPermissionGrant -Scope Global -Force
   Set-Alias -Name Remove-AzureADDomain -Value Remove-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Get-AzureADScopedRoleMembership -Value Get-EntraBetaScopedRoleMembership -Scope Global -Force
   Set-Alias -Name Get-AzureADDeletedApplication -Value Get-EntraBetaDeletedApplication -Scope Global -Force
   Set-Alias -Name Remove-AzureADDeviceRegisteredOwner -Value Remove-EntraBetaDeviceRegisteredOwner -Scope Global -Force
   Set-Alias -Name Get-AzureADMSIdentityProvider -Value Get-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationKeyCredential -Value Get-EntraBetaApplicationKeyCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADUserOwnedDevice -Value Get-EntraBetaUserOwnedDevice -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationPolicy -Value Get-EntraBetaApplicationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalMembership -Value Get-EntraBetaServicePrincipalMembership -Scope Global -Force
   Set-Alias -Name Get-AzureADPolicy -Value Get-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSInvitation -Value New-EntraBetaInvitation -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSDeletedDirectoryObject -Value Remove-EntraBetaDeletedDirectoryObject -Scope Global -Force
   Set-Alias -Name Remove-AzureADAdministrativeUnitMember -Value Remove-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPrivilegedResource -Value Get-EntraBetaPrivilegedResource -Scope Global -Force
   Set-Alias -Name Set-AzureADMSCustomSecurityAttributeDefinitionAllowedValue -Value Set-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name New-AzureADMSIdentityProvider -Value New-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationExtensionProperty -Value Get-EntraBetaApplicationExtensionProperty -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSLifecyclePolicyGroup -Value Remove-EntraBetaLifecyclePolicyGroup -Scope Global -Force
   Set-Alias -Name Get-AzureADMSFeatureRolloutPolicy -Value Get-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSPasswordSingleSignOnCredential -Value Remove-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceRegisteredUser -Value Get-EntraBetaDeviceRegisteredUser -Scope Global -Force
   Set-Alias -Name Remove-AzureADGroupMember -Value Remove-EntraBetaGroupMember -Scope Global -Force
   Set-Alias -Name New-AzureADMSConditionalAccessPolicy -Value New-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Update-AzureADSignedInUserPassword -Value Set-EntraBetaSignedInUserPassword -Scope Global -Force
   Set-Alias -Name Set-AzureADMSAdministrativeUnit -Value Set-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name Get-AzureADUserOAuth2PermissionGrant -Value Get-EntraBetaUserOAuth2PermissionGrant -Scope Global -Force
   Set-Alias -Name New-AzureADPrivilegedRoleAssignment -Value New-EntraBetaPrivilegedRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADUserExtension -Value Get-EntraBetaUserExtension -Scope Global -Force
   Set-Alias -Name New-AzureADTrustedCertificateAuthority -Value New-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name Get-AzureADMSNamedLocationPolicy -Value Get-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationLogo -Value Get-EntraBetaApplicationLogo -Scope Global -Force
   Set-Alias -Name Remove-AzureADDeviceRegisteredUser -Value Remove-EntraBetaDeviceRegisteredUser -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipalPasswordCredential -Value New-EntraBetaServicePrincipalPasswordCredential -Scope Global -Force
   Set-Alias -Name New-AzureADMSRoleDefinition -Value New-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPermissionGrantConditionSet -Value Set-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name Get-AzureADMSServicePrincipalDelegatedPermissionClassification -Value Get-EntraBetaServicePrincipalDelegatedPermissionClassification -Scope Global -Force
   Set-Alias -Name Set-AzureADMSAttributeSet -Value Set-EntraBetaAttributeSet -Scope Global -Force
   Set-Alias -Name Get-AzureADApplication -Value Get-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name Get-AzureADMSTrustFrameworkPolicy -Value Get-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyApplication -Value Remove-EntraBetaApplicationProxyApplication -Scope Global -Force
   Set-Alias -Name Get-AzureADDevice -Value Get-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name New-AzureADObjectSetting -Value New-EntraBetaObjectSetting -Scope Global -Force
   Set-Alias -Name New-AzureADPolicy -Value New-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSCustomSecurityAttributeDefinition -Value Set-EntraBetaCustomSecurityAttributeDefinition -Scope Global -Force
   Set-Alias -Name Get-AzureADContact -Value Get-EntraBetaContact -Scope Global -Force
   Set-Alias -Name Remove-AzureADPolicy -Value Remove-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSConditionalAccessPolicy -Value Remove-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Add-AzureADAdministrativeUnitMember -Value Add-EntraBetaAdministrativeUnitMember -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalKeyCredential -Value Get-EntraBetaServicePrincipalKeyCredential -Scope Global -Force
   Set-Alias -Name Set-AzureADDevice -Value Set-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name Set-AzureADTrustedCertificateAuthority -Value Set-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name Select-AzureADGroupIdsServicePrincipalIsMemberOf -Value Select-EntraBetaGroupIdsServicePrincipalIsMemberOf -Scope Global -Force
   Set-Alias -Name Set-AzureADUserThumbnailPhoto -Value Set-EntraBetaUserThumbnailPhoto -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPasswordSingleSignOnCredential -Value Set-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADPrivilegedRole -Value Get-EntraBetaPrivilegedRole -Scope Global -Force
   Set-Alias -Name Remove-AzureADGroupAppRoleAssignment -Value Remove-EntraBetaGroupAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Remove-AzureADContact -Value Remove-EntraBetaContact -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationExtensionProperty -Value Remove-EntraBetaApplicationExtensionProperty -Scope Global -Force
   Set-Alias -Name Get-AzureADContactMembership -Value Get-EntraBetaContactMembership -Scope Global -Force
   Set-Alias -Name Remove-AzureADGroupOwner -Value Remove-EntraBetaGroupOwner -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationPolicy -Value Remove-EntraBetaApplicationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADContactDirectReport -Value Get-EntraBetaContactDirectReport -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipal -Value Remove-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name Add-AzureADApplicationOwner -Value Add-EntraBetaApplicationOwner -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSTrustFrameworkPolicy -Value Remove-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name Add-AzureADGroupOwner -Value Add-EntraBetaGroupOwner -Scope Global -Force
   Set-Alias -Name Restore-AzureADDeletedApplication -Value Restore-EntraBetaDeletedApplication -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPrivilegedRoleSetting -Value Set-EntraBetaPrivilegedRoleSetting -Scope Global -Force
   Set-Alias -Name Get-AzureADGroup -Value Get-EntraBetaGroup -Scope Global -Force
   Set-Alias -Name Get-AzureADMSDeletedGroup -Value Get-EntraBetaDeletedGroup -Scope Global -Force
   Set-Alias -Name New-AzureADDevice -Value New-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name Add-AzureADMSLifecyclePolicyGroup -Value Add-EntraBetaLifecyclePolicyGroup -Scope Global -Force
   Set-Alias -Name New-AzureADUser -Value New-EntraBetaUser -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplicationKey -Value New-EntraBetaApplicationKey -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationPasswordCredential -Value Remove-EntraBetaApplicationPasswordCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADUserAppRoleAssignment -Value Get-EntraBetaUserAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Remove-AzureADUserManager -Value Remove-EntraBetaUserManager -Scope Global -Force
   Set-Alias -Name New-AzureADMSRoleAssignment -Value New-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectorySettingTemplate -Value Get-EntraBetaDirectorySettingTemplate -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalOwnedObject -Value Get-EntraBetaServicePrincipalOwnedObject -Scope Global -Force
   Set-Alias -Name Set-AzureADMSTrustFrameworkPolicy -Value Set-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSCustomSecurityAttributeDefinition -Value Get-EntraBetaCustomSecurityAttributeDefinition -Scope Global -Force
   Set-Alias -Name Remove-AzureADAdministrativeUnit -Value Remove-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPermissionGrantPolicy -Value Get-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADDomain -Value New-EntraBetaDomain -Scope Global -Force
   Set-Alias -Name Add-AzureADScopedRoleMembership -Value Add-EntraBetaScopedRoleMembership -Scope Global -Force
   Set-Alias -Name Remove-AzureADObjectSetting -Value Remove-EntraBetaObjectSetting -Scope Global -Force
   Set-Alias -Name Set-AzureADUser -Value Set-EntraBetaUser -Scope Global -Force
   Set-Alias -Name Add-AzureADServicePrincipalOwner -Value Add-EntraBetaServicePrincipalOwner -Scope Global -Force
   Set-Alias -Name Remove-AzureADOAuth2PermissionGrant -Value Remove-EntraBetaOAuth2PermissionGrant -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSFeatureRolloutPolicyDirectoryObject -Value Remove-EntraBetaFeatureRolloutPolicyDirectoryObject -Scope Global -Force
   Set-Alias -Name Add-AzureADServicePrincipalPolicy -Value Add-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADDirectoryRoleMember -Value Remove-EntraBetaDirectoryRoleMember -Scope Global -Force
   Set-Alias -Name New-AzureADServiceAppRoleAssignment -Value New-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name New-AzureADMSNamedLocationPolicy -Value New-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADDirectorySetting -Value Get-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Remove-AzureADDevice -Value Remove-EntraBetaDevice -Scope Global -Force
   Set-Alias -Name Get-AzureADAdministrativeUnit -Value Get-EntraBetaAdministrativeUnit -Scope Global -Force
   Set-Alias -Name Get-AzureADDomainServiceConfigurationRecord -Value Get-EntraBetaDomainServiceConfigurationRecord -Scope Global -Force
   Set-Alias -Name Set-AzureADUserLicense -Value Set-EntraBetaUserLicense -Scope Global -Force
   Set-Alias -Name Remove-AzureADDirectorySetting -Value Remove-EntraBetaDirectorySetting -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPrivilegedRoleAssignmentRequest -Value Set-EntraBetaPrivilegedRoleAssignmentRequest -Scope Global -Force
   Set-Alias -Name Add-AzureADMSServicePrincipalDelegatedPermissionClassification -Value Add-EntraBetaServicePrincipalDelegatedPermissionClassification -Scope Global -Force
   Set-Alias -Name Set-AzureADMSConditionalAccessPolicy -Value Set-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSFeatureRolloutPolicy -Value Set-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceRegisteredOwner -Value Get-EntraBetaDeviceRegisteredOwner -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPermissionGrantConditionSet -Value Get-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name Remove-AzureADUser -Value Remove-EntraBetaUser -Scope Global -Force
   Set-Alias -Name Get-AzureADMSConditionalAccessPolicy -Value Get-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADAuditDirectoryLogs -Value Get-EntraBetaAuditDirectoryLog -Scope Global -Force
   Set-Alias -Name Get-AzureADOAuth2PermissionGrant -Value Get-EntraBetaOAuth2PermissionGrant -Scope Global -Force
   Set-Alias -Name Get-AzureADContract -Value Get-EntraBetaContract -Scope Global -Force
   Set-Alias -Name Get-AzureADUserDirectReport -Value Get-EntraBetaUserDirectReport -Scope Global -Force
   Set-Alias -Name Get-CrossCloudVerificationCode -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationCustomDomainCertificate -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Open-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationSingleSignOn -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADContactThumbnailPhoto -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADCurrentSessionInfo -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Close-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADContactManager -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationPasswordCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceConfiguration -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Restore-AzureADMSDeletedDirectoryObject -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorMemberOf -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroupMembers -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Add-AzureADMSPrivilegedResource -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADPrivilegedRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExtensionProperty -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationServiceEndpoint -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Connect-AzureAD -Value Connect-EntraBeta -Scope Global -Force
   Set-Alias -Name Disconnect-AzureAD -Value Disconnect-EntraBeta -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaRoleAssignment -Value Remove-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleAssignment -Value Get-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name New-EntraBetaRoleAssignment -Value New-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Set-EntraBetaRoleDefinition -Value Set-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleDefinition -Value Get-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaRoleDefinition -Value Remove-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name New-EntraBetaRoleDefinition -Value New-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Get-EntraBetaServiceAppRoleAssignedTo -Value Get-EntraBetaServicePrincipalAppRoleAssignedTo -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaServiceAppRoleAssignment -Value Remove-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-EntraBetaServiceAppRoleAssignment -Value Get-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name New-EntraBetaServiceAppRoleAssignment -Value New-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValues -Value Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name Get-EntraBetaAuditDirectoryLogs -Value Get-EntraBetaAuditDirectoryLog -Scope Global -Force
   Set-Alias -Name Get-EntraBetaAuditSignInLogs -Value Get-EntraBetaAuditSignInLog -Scope Global -Force
}

