# ------------------------------------------------------------------------------ 
#  Copyright (c) Microsoft Corporation.  All Rights Reserved.  
#  Licensed under the MIT License.  See License in the project root for license information. 
# ------------------------------------------------------------------------------ 
function Enable-EntraAzureADAliases {
   Set-Alias -Name Remove-AzureADMSPasswordSingleSignOnCredential -Value Remove-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyApplication -Value Get-EntraBetaApplicationProxyApplication -Scope Global -Force
   Set-Alias -Name Remove-AzureADDeletedApplication -Value Remove-EntraBetaDeletedApplication -Scope Global -Force
   Set-Alias -Name Get-AzureADDeletedApplication -Value Get-EntraBetaDeletedApplication -Scope Global -Force
   Set-Alias -Name Add-AzureADMSServicePrincipalDelegatedPermissionClassification -Value Add-EntraBetaServicePrincipalDelegatedPermissionClassification -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplicationFromApplicationTemplate -Value New-EntraBetaApplicationFromApplicationTemplate -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationPolicy -Value Remove-EntraBetaApplicationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationSignInDetailedSummary -Value Get-EntraBetaApplicationSignInDetailedSummary -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplicationPassword -Value New-EntraBetaApplicationPassword -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationPasswordCredential -Value New-EntraBetaApplicationPasswordCredential -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalPolicy -Value Remove-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSApplicationTemplate -Value Get-EntraBetaApplicationTemplate -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalOwner -Value Remove-EntraBetaServicePrincipalOwner -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSApplicationPassword -Value Remove-EntraBetaApplicationPassword -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalPasswordCredential -Value Remove-EntraBetaServicePrincipalPasswordCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationPolicy -Value Get-EntraBetaApplicationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADApplication -Value Get-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipalPasswordCredential -Value New-EntraBetaServicePrincipalPasswordCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipal -Value Get-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplication -Value New-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name Add-AzureADApplicationPolicy -Value Add-EntraBetaApplicationPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADServiceAppRoleAssignment -Value Get-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationLogo -Value Get-EntraBetaApplicationLogo -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalOAuth2PermissionGrant -Value Get-EntraBetaServicePrincipalOAuth2PermissionGrant -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipal -Value New-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name Get-AzureADMSServicePrincipalDelegatedPermissionClassification -Value Get-EntraBetaServicePrincipalDelegatedPermissionClassification -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPasswordSingleSignOnCredential -Value Set-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPasswordSingleSignOnCredential -Value Get-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalKeyCredential -Value Get-EntraBetaServicePrincipalKeyCredential -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSServicePrincipalDelegatedPermissionClassification -Value Remove-EntraBetaServicePrincipalDelegatedPermissionClassification -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationExtensionProperty -Value Remove-EntraBetaApplicationExtensionProperty -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalOwnedObject -Value Get-EntraBetaServicePrincipalOwnedObject -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationKeyCredential -Value Remove-EntraBetaApplicationKeyCredential -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipal -Value Remove-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationSignInSummary -Value Get-EntraBetaApplicationSignInSummary -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyApplication -Value Remove-EntraBetaApplicationProxyApplication -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalMembership -Value Get-EntraBetaServicePrincipalMembership -Scope Global -Force
   Set-Alias -Name Set-AzureADServicePrincipal -Value Set-EntraBetaServicePrincipal -Scope Global -Force
   Set-Alias -Name New-AzureADMSPasswordSingleSignOnCredential -Value New-EntraBetaPasswordSingleSignOnCredential -Scope Global -Force
   Set-Alias -Name Add-AzureADServicePrincipalOwner -Value Add-EntraBetaServicePrincipalOwner -Scope Global -Force
   Set-Alias -Name Add-AzureADApplicationOwner -Value Add-EntraBetaApplicationOwner -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationKeyCredential -Value Get-EntraBetaApplicationKeyCredential -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalOwner -Value Get-EntraBetaServicePrincipalOwner -Scope Global -Force
   Set-Alias -Name Restore-AzureADDeletedApplication -Value Restore-EntraBetaDeletedApplication -Scope Global -Force
   Set-Alias -Name Select-AzureADGroupIdsServicePrincipalIsMemberOf -Value Select-EntraBetaGroupIdsServicePrincipalIsMemberOf -Scope Global -Force
   Set-Alias -Name Set-AzureADMSApplication -Value Set-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationPasswordCredential -Value Remove-EntraBetaApplicationPasswordCredential -Scope Global -Force
   Set-Alias -Name Remove-AzureADServiceAppRoleAssignment -Value Remove-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Set-AzureADMSApplicationVerifiedPublisher -Value Set-EntraBetaApplicationVerifiedPublisher -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalCreatedObject -Value Get-EntraBetaServicePrincipalCreatedObject -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationExtensionProperty -Value New-EntraBetaApplicationExtensionProperty -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationLogo -Value Set-EntraBetaApplicationLogo -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationOwner -Value Get-EntraBetaApplicationOwner -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSApplicationKey -Value Remove-EntraBetaApplicationKey -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationExtensionProperty -Value Get-EntraBetaApplicationExtensionProperty -Scope Global -Force
   Set-Alias -Name New-AzureADServiceAppRoleAssignment -Value New-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplication -Value Remove-EntraBetaApplication -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationKeyCredential -Value New-EntraBetaApplicationKeyCredential -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationOwner -Value Remove-EntraBetaApplicationOwner -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSDeletedDirectoryObject -Value Remove-EntraBetaDeletedDirectoryObject -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalPolicy -Value Get-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalPasswordCredential -Value Get-EntraBetaServicePrincipalPasswordCredential -Scope Global -Force
   Set-Alias -Name New-AzureADMSApplicationKey -Value New-EntraBetaApplicationKey -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSApplicationVerifiedPublisher -Value Remove-EntraBetaApplicationVerifiedPublisher -Scope Global -Force
   Set-Alias -Name Get-AzureADServiceAppRoleAssignedTo -Value Get-EntraBetaServicePrincipalAppRoleAssignedTo -Scope Global -Force
   Set-Alias -Name Get-CrossCloudVerificationCode -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationPasswordCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExtensionProperty -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationServiceEndpoint -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Restore-AzureADMSDeletedDirectoryObject -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADPrivilegedRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorMemberOf -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Close-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceConfiguration -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationSingleSignOn -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Open-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationCustomDomainCertificate -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Add-AzureADMSPrivilegedResource -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroupMembers -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADCurrentSessionInfo -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADContactManager -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADContactThumbnailPhoto -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-EntraBetaServiceAppRoleAssignedTo -Value Get-EntraBetaServicePrincipalAppRoleAssignedTo -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaServiceAppRoleAssignment -Value Remove-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-EntraBetaServiceAppRoleAssignment -Value Get-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name New-EntraBetaServiceAppRoleAssignment -Value New-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force

}
