# ------------------------------------------------------------------------------ 
#  Copyright (c) Microsoft Corporation.  All Rights Reserved.  
#  Licensed under the MIT License.  See License in the project root for license information. 
# ------------------------------------------------------------------------------ 
function Enable-EntraAzureADAliases {
   Set-Alias -Name Set-AzureADMSIdentityProvider -Value Set-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name New-AzureADMSInvitation -Value New-EntraBetaInvitation -Scope Global -Force
   Set-Alias -Name Get-AzureADMSIdentityProvider -Value Get-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPermissionGrantPolicy -Value Get-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name Add-AzureADServicePrincipalPolicy -Value Add-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADPolicy -Value Set-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSNamedLocationPolicy -Value New-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSNamedLocationPolicy -Value Set-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSConditionalAccessPolicy -Value Remove-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSConditionalAccessPolicy -Value Get-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalPolicy -Value Remove-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADPolicy -Value New-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPermissionGrantConditionSet -Value Set-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name New-AzureADMSPermissionGrantConditionSet -Value New-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name Set-AzureADMSPermissionGrantPolicy -Value Set-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSPermissionGrantPolicy -Value New-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADTrustedCertificateAuthority -Value New-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSFeatureRolloutPolicyDirectoryObject -Value Remove-EntraBetaFeatureRolloutPolicyDirectoryObject -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSIdentityProvider -Value Remove-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name Get-AzureADPolicy -Value Get-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSTrustFrameworkPolicy -Value New-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSAuthorizationPolicy -Value Get-EntraBetaAuthorizationPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSPermissionGrantPolicy -Value Remove-EntraBetaPermissionGrantPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSNamedLocationPolicy -Value Get-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSIdentityProvider -Value New-EntraBetaIdentityProvider -Scope Global -Force
   Set-Alias -Name Get-AzureADOAuth2PermissionGrant -Value Get-EntraBetaOAuth2PermissionGrant -Scope Global -Force
   Set-Alias -Name New-AzureADMSFeatureRolloutPolicy -Value New-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADPolicyAppliedObject -Value Get-EntraBetaPolicyAppliedObject -Scope Global -Force
   Set-Alias -Name Get-AzureADMSFeatureRolloutPolicy -Value Get-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name Add-AzureADMSFeatureRolloutPolicyDirectoryObject -Value Add-EntraBetaFeatureRolloutPolicyDirectoryObject -Scope Global -Force
   Set-Alias -Name Set-AzureADMSFeatureRolloutPolicy -Value Set-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADTrustedCertificateAuthority -Value Set-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSTrustFrameworkPolicy -Value Remove-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name New-AzureADMSConditionalAccessPolicy -Value New-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSAuthorizationPolicy -Value Set-EntraBetaAuthorizationPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSPermissionGrantConditionSet -Value Remove-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name Remove-AzureADPolicy -Value Remove-EntraBetaPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSTrustFrameworkPolicy -Value Set-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADMSPermissionGrantConditionSet -Value Get-EntraBetaPermissionGrantConditionSet -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSNamedLocationPolicy -Value Remove-EntraBetaNamedLocationPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADMSFeatureRolloutPolicy -Value Remove-EntraBetaFeatureRolloutPolicy -Scope Global -Force
   Set-Alias -Name Set-AzureADMSConditionalAccessPolicy -Value Set-EntraBetaConditionalAccessPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADTrustedCertificateAuthority -Value Remove-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name Get-AzureADMSTrustFrameworkPolicy -Value Get-EntraBetaTrustFrameworkPolicy -Scope Global -Force
   Set-Alias -Name Get-AzureADTrustedCertificateAuthority -Value Get-EntraBetaTrustedCertificateAuthority -Scope Global -Force
   Set-Alias -Name Get-AzureADServicePrincipalPolicy -Value Get-EntraBetaServicePrincipalPolicy -Scope Global -Force
   Set-Alias -Name Remove-AzureADOAuth2PermissionGrant -Value Remove-EntraBetaOAuth2PermissionGrant -Scope Global -Force
   Set-Alias -Name Get-CrossCloudVerificationCode -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-RbacApplicationRoleDefinition -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationPasswordCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExtensionProperty -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationServiceEndpoint -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Restore-AzureADMSDeletedDirectoryObject -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADPrivilegedRoleAssignment -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorMemberOf -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Close-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADDeviceConfiguration -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationSingleSignOn -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Open-AzureADMSPrivilegedRoleAssignmentRequest -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADExternalDomainFederation -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationCustomDomainCertificate -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Add-AzureADMSPrivilegedResource -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroupMembers -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADCurrentSessionInfo -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADContactManager -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADApplicationProxyApplicationConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name New-AzureADApplicationProxyApplication -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Remove-AzureADServicePrincipalKeyCredential -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Set-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADContactThumbnailPhoto -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnectorGroup -Value Get-EntraUnsupportedCommand -Scope Global -Force
   Set-Alias -Name Get-AzureADApplicationProxyConnector -Value Get-EntraUnsupportedCommand -Scope Global -Force

}
