   Set-Alias -Name Connect-AzureAD -Value Connect-EntraBeta -Scope Global -Force
   Set-Alias -Name Disconnect-AzureAD -Value Disconnect-EntraBeta -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaRoleAssignment -Value Remove-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleAssignment -Value Get-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name New-EntraBetaRoleAssignment -Value New-EntraBetaDirectoryRoleAssignment -Scope Global -Force
   Set-Alias -Name Set-EntraBetaRoleDefinition -Value Set-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Get-EntraBetaRoleDefinition -Value Get-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaRoleDefinition -Value Remove-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name New-EntraBetaRoleDefinition -Value New-EntraBetaDirectoryRoleDefinition -Scope Global -Force
   Set-Alias -Name Get-EntraBetaServiceAppRoleAssignedTo -Value Get-EntraBetaServicePrincipalAppRoleAssignedTo -Scope Global -Force
   Set-Alias -Name Remove-EntraBetaServiceAppRoleAssignment -Value Remove-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Get-EntraBetaServiceAppRoleAssignment -Value Get-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name New-EntraBetaServiceAppRoleAssignment -Value New-EntraBetaServicePrincipalAppRoleAssignment -Scope Global -Force
   Set-Alias -Name Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValues -Value Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValue -Scope Global -Force
   Set-Alias -Name Get-EntraBetaAuditDirectoryLogs -Value Get-EntraBetaAuditDirectoryLog -Scope Global -Force
   Set-Alias -Name Get-EntraBetaAuditSignInLogs -Value Get-EntraBetaAuditSignInLog -Scope Global -Force
