trigger:
- none
pool:
  name: default

stages:
- stage: PS_Gallery_Deploy
  displayName: PS Gallery Deploy
  jobs:
  - job: Install_Dependencies
    displayName: Install dependencies
    steps:
    - task: PowerShell@2
      displayName: Version Check
      inputs:
        targetType: inline
        pwsh: true
        script: |
          Write-Output $PSVersionTable
  - job: Release_Approval
    displayName: Agentless job
    pool:
      type: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: ''
        instructions: 'Please validate the build configuration and resume'
        onTimeout: reject
      enabled: false
      timeoutInMinutes: 6120

  - job: PsGallery_Push
    displayName: Push to PS Gallery
    pool:
      type: server
    timeoutInMinutes: 6120
    steps:
    - task: powershell@2
      inputs:
        targetType: inline
        script: |
          Publish-Module -NuGetApiKey $env:NuGetApiKey -Path $(Build.ArtifactStagingDirectory)/modules/Microsoft.Entra -Verbose
          Publish-Module -NuGetApiKey $env:NuGetApiKey -Path $(Build.ArtifactStagingDirectory)/modules/Microsoft.Entra.Beta -Verbose
        pwsh: false
    dependsOn: Release_Approval