# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# https://aka.ms/yaml

variables:
  TEST_OUTPUT_DIRECTORY: './test/results'
  TEST_OUTPUT_FILE: pester-testresults.xml

steps:
- task: powershell@2
  displayName: 'Show current PowerShell version information'
  inputs:
    targetType: inline
    script: 'echo $PSVersionTable'
    pwsh: false

- task: powershell@2
  displayName: 'Install Pester'
  inputs:
    targetType: inline
    script: Install-Module Pester -scope currentuser -Force
    pwsh: false

- task: powershell@2
  displayName: 'Run tests'  
  inputs:
    targetType: inline
    pwsh: false
    script: |
      si env:TEST_OUTPUT_PATH "$($env:TEST_OUTPUT_DIRECTORY)/$($env:TEST_OUTPUT_FILE)"      
      Invoke-Pester -OutputFile $env:TEST_OUTPUT_PATH -OutputFormat NUnitXml

- task: PublishTestResults@2
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: $(TEST_OUTPUT_DIRECTORY)/$(TEST_OUTPUT_FILE)
    failTaskOnFailedTests: true